# Generated by Django 2.2.10 on 2020-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disguise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
